index/urls.py
from django.urls import path
from .views import redirect_to_github

app_name = 'index'

urlpatterns = [
	path('', redirect_to_github, name='redirect_to_github'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('index.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, register, login_user, logout_user, create_task, show_todolist_json, show_todolist_ajax, api_done, api_undone, api_delete, api_add

app_name = 'todolist'

urlpatterns = [
	path('', show_todolist_ajax, name='todolist'),
	path('login', login_user, name='login'),
	path('register', register, name='register'),
	path('create-task', create_task, name='create_task'),
	path('logout', logout_user, name='logout'),
	path('old', show_todolist, name='todolist_old'),
	path('json', show_todolist_json, name='todolist_json'),

	# API (no prefix)
	path('add', api_add, name="api_add"),
	path('done/<int:id>', api_done, name="api_done"),
	path('undone/<int:id>', api_undone, name="api_undone"),
	path('delete/<int:id>', api_delete, name="api_delete"),

	# API (api/ prefix)
	path('api/add', api_add, name="api_add_2"),
	path('api/done/<int:id>', api_done, name="api_done_2"),
	path('api/undone/<int:id>', api_undone, name="api_undone_2"),
	path('api/delete/<int:id>', api_delete, name="api_delete_2"),

]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateField()
	title = models.CharField(max_length=255)
	description = models.TextField()
	is_finished = models.BooleanField()

	def __str__(self) -> str:
		return str(self.user) + ': ' + self.title

todolist/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

    def __str__(self):
        return ""

todolist/views.py
import json
from django.shortcuts import render
from todolist.models import Task
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import requires_csrf_token
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TaskForm

@login_required(login_url='/todolist/login')
@requires_csrf_token
def show_todolist(request):
	
	if request.method == "POST":
		pk = request.POST['id']
		action = request.POST['action']
		tasks = Task.objects.filter(pk=pk)
		if len(tasks) == 0:
			messages.warning(request, 'Task tidak tersedia untuk diperbarui. Coba lagi.')
		elif len(tasks) > 1:
			messages.warning(request, 'Terdapat teralu banyak task yang cocok. Coba lagi.')
		else:
			task = tasks[0]
			if action == 'done':
				task.is_finished = True
				task.save()
				messages.success(request, 'Task telah berhasil diperbarui!')
			elif action == 'undone':
				task.is_finished = False
				task.save()
				messages.success(request, 'Task telah berhasil diperbarui!')
			elif action == 'delete':
				task.delete()
				messages.success(request, 'Task telah berhasil dihapus!')


	data = Task.objects.filter(user=request.user)

	context = {
		'data': data,
		# 'last_login': request.COOKIES['last_login'],
	}

	return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login')
def create_task(request):
	form = TaskForm()

	if request.method == "POST":
		form = TaskForm(request.POST, instance=Task())
		if form.is_valid():
			to_save = form.save(commit=False)
			to_save.user = request.user
			to_save.date = datetime.date.today()
			to_save.is_finished = False
			to_save.save()
			form.save_m2m()
			messages.success(request, 'Task telah berhasil ditambah!')
			return redirect('todolist:todolist')
	
	context = {
		'form': form,
		# 'last_login': request.COOKIES['last_login'],
	}
	return render(request, 'create-task.html', context)

def register(request):
	form = UserCreationForm()

	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Akun telah berhasil dibuat!')
			return redirect('todolist:login')
	
	context = {'form':form}
	return render(request, 'register.html', context)

def login_user(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			response = HttpResponseRedirect(reverse("todolist:todolist"))
			# response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
			return response
		else:
			messages.info(request, 'Username atau password salah!')
	context = {}
	return render(request, 'login.html', context)

def logout_user(request):
	logout(request)
	response = HttpResponseRedirect(reverse('todolist:login'))
	# response.delete_cookie('last_login')
	messages.info(request, 'Anda telah berhasil keluar!')
	return response

def apires_ok(request):
	data = Task.objects.filter(user=request.user)
	return HttpResponse(serializers.serialize("json", data), content_type="application/json", status=200)

def apires_bad_request():
	return HttpResponse(status=400)

def apires_unauthorized():
	return HttpResponse(status=403)

def show_todolist_json(request):

	if request.user.is_authenticated:
		data = Task.objects.filter(user=request.user)
	else:
		data = {}

	return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login')
def show_todolist_ajax(request):	
	return render(request, "todolist-ajax.html", {})

def api_done(request, id):
	if not request.user.is_authenticated:
		return apires_unauthorized()
	# if not (request.method == "POST" or request.method == "PATCH"):
	# 	return apires_bad_response()
	if not id: 
		return apires_bad_request()
	
	tasks = Task.objects.filter(pk=id, user=request.user)
	if len(tasks) != 1:
		return apires_bad_request()
	
	task = tasks[0]
	task.is_finished = True
	task.save()

	return apires_ok(request)

def api_undone(request, id):
	if not request.user.is_authenticated:
		return apires_unauthorized()
	# if not (request.method == "POST" or request.method == "PATCH"):
	# 	return apires_bad_response()
	if not id: 
		return apires_bad_request()
	
	tasks = Task.objects.filter(pk=id, user=request.user)
	if len(tasks) != 1:
		return apires_bad_request()
	
	task = tasks[0]
	task.is_finished = False
	task.save()

	return apires_ok(request)

def api_delete(request, id):
	if not request.user.is_authenticated:
		return apires_unauthorized()
	# if not (request.method == "DELETE" or request.method == "POST"):
	# 	return apires_bad_response()
	if not id: 
		return apires_bad_request()
	
	tasks = Task.objects.filter(pk=id, user=request.user)
	if len(tasks) != 1:
		return apires_bad_request()
	
	task = tasks[0]
	task.delete()

	return apires_ok(request)

def api_add(request):
	if not request.user.is_authenticated:
		return apires_unauthorized()
	if not request.method == "POST":
		return apires_bad_request()

	form = TaskForm()

	if request.method != "POST":
		return apires_bad_request()

	form = TaskForm(json.loads(request.body), instance=Task())
	if not form.is_valid():
		return apires_bad_request()

	to_save = form.save(commit=False)
	to_save.user = request.user
	to_save.date = datetime.date.today()
	to_save.is_finished = False
	to_save.save()
	form.save_m2m()
	
	data = Task.objects.filter(user=request.user)
	return HttpResponse(serializers.serialize("json", data), content_type="application/json", status=201)

todolist/templates/create-task.html
{% extends 'base_tw.html' %}

{% block meta %}
<title>Buat Task • Hans TM @ Tugas PBP</title>
{% endblock meta %}

{% block content %}

<body class="bg-gradient-to-br from-orange-600 to-amber-400 h-full min-h-screen w-full p-4">
	<!-- <div class="max-w-[48rem] min-w-[24rem] m-auto bg-white rounded-md p-8 shadow-lg">
	</div> -->

	{% include 'navbar.html' %}

	<div class="max-w-[48rem] min-w-[24rem] m-auto bg-white rounded-md p-8 shadow-md hover:shadow-xl transition">

		<h1 class="text-4xl font-semibold mb-4">Buat Task</h1>

		{% if messages %}
		<div class="mb-4 bg-sky-200 py-2 px-3 rounded-md border-sky-300 border-2">
			<ul>
				{% for message in messages %}
				<li>{{ message }}</li>
				{% endfor %}
			</ul>
		</div>
		{% endif %}

		<form method="POST" class="mb-3">
			{% csrf_token %}
			<div class="mb-3">
				<label for="inputTitle" class="mb-1 block">Judul</label>
				<input type="text" name="title" id="inputTitle" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-red-500 focus:invalid:ring-red-500 transition" required>
			</div>
			<div class="mb-3">
				<label for="inputDescription" class="mb-1 block">Keterangan</label>
				<textarea type="text" name="description" id="inputDescription" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-pink-500 focus:invalid:ring-red-500 transition" required></textarea>
			</div>
			<button class="py-2 px-3 bg-blue-500 text-white hover:bg-blue-600 focus:ring focus:ring-blue-200 rounded-md shadow-sm transition" type="submit">Tambah</button>
		</form>

	</div>

</body>

{% endblock content %}

todolist/templates/login.html
{% extends 'base_tw.html' %}

{% block meta %}
<title>Masuk • To-Do List • Hans TM @ Tugas PBP</title>
{% endblock meta %}

{% block content %}

<body class="bg-gradient-to-br from-orange-600 to-amber-400 h-full min-h-screen w-full flex items-center justify-center">
	<div class="max-w-[48rem] m-4 bg-white rounded-md p-8 shadow-md hover:shadow-xl transition">

		<h1 class="text-4xl font-semibold mb-4">Masuk</h1>

		{% if messages %}
		<div class="mb-4 bg-sky-200 py-2 px-3 rounded-md border-sky-300 border-2">
			<ul>
				{% for message in messages %}
				<li>{{ message }}</li>
				{% endfor %}
			</ul>
		</div>
		{% endif %}

		<form method="POST" action="" class="mb-3">
			{% csrf_token %}
			<div class="mb-3">
				<label for="inputUserName" class="mb-1 block">Username</label>
				<input type="text" name="username" id="inputUserName" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-red-500 focus:invalid:ring-red-500 transition" required>
			</div>
			<div class="mb-3">
				<label for="inputPassword" class="mb-1 block font">Password</label>
				<input type="password" name="password" id="inputPassword" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-red-500 focus:invalid:ring-red-500 transition" required>
			</div>
			<button class="py-2 px-3 bg-blue-600 text-white hover:bg-blue-700 disabled:bg-blue-400 focus:ring focus:ring-blue-200 rounded-md shadow-sm transition" type="submit">Login</button>
		</form>


		<p>Belum mempunyai akun? <a href="{% url 'todolist:register' %}" class="text-blue-600 hover:text-blue-900 transition">Buat akun</a>.</p>

	</div>
</body>

{% endblock content %}

todolist/templates/navbar.html
<header class="bg-white p-2 rounded-md shadow-md mb-4 hover:shadow-xl transition">
	<nav class="flex gap-1">
		<a href="{% url 'todolist:todolist' %}" class="py-2 px-4 rounded-md bg-slate-100 hover:bg-slate-300 transition">📝 To-Do List</a>
		<a href="{% url 'todolist:create_task' %}" class="py-2 px-4 rounded-md bg-slate-100 hover:bg-slate-300 transition">➕ Buat Task</a>
		<span class="py-2 group relative ml-auto">
			<span class="py-2 px-4 rounded-md bg-slate-100 hover:bg-slate-300 transition cursor-pointer">👤 {{ request.user }}</span>
			<div class="absolute pt-3 hidden group-hover:block right-0 transition">
				<div class="shadow-md rounded bg-white ring ring-slate-900/5 py-2 w-32">
					<a class="px-4 py-2 bg-white hover:bg-slate-200 w-full block transition" href="{% url 'todolist:logout' %}">🚪 Keluar</a>
				</div>
			</div>
		</span>
	</nav>
</header>

todolist/templates/register.html
{% extends 'base_tw.html' %}

{% block meta %}
<title>Pendaftaran • To-Do List • Hans TM @ Tugas PBP</title>
{% endblock meta %}

{% block content %}

<body class="bg-gradient-to-br from-orange-600 to-amber-400 h-full min-h-screen w-full flex items-center justify-center">
	<div class="max-w-[48rem] m-4 bg-white rounded-md p-8 shadow-md hover:shadow-xl transition">

		<h1 class="text-4xl font-semibold mb-4">Daftar</h1>

		{% if messages %}
		<div class="mb-4 bg-sky-200 py-2 px-3 rounded-md border-sky-300 border-2">
			<ul>
				{% for message in messages %}
				<li>{{ message }}</li>
				{% endfor %}
			</ul>
		</div>
		{% endif %}

		<form method="POST" class="mb-3">
			{% csrf_token %}
			<div class="mb-3">
				<label for="inputUserName" class="mb-1 block">Username</label>
				<input type="text" name="username" id="inputUserName" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-red-500 focus:invalid:ring-red-500 transition" required>
				<p class="text-xs">150 karakter atau kurang. Huruf, angka dan @/./+/-/_ saja.</p>
			</div>
			<div class="mb-3">
				<label for="inputPassword" class="mb-1 block">Password</label>
				<input type="password" name="password1" id="inputPassword" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-pink-500 focus:invalid:ring-red-500 transition" required>
				<ul class="text-xs">
					<li>Password Anda tidak boleh terlalu mirip dengan informasi pribadi Anda yang lain.</li>
					<li>Password Anda harus mengandung setidaknya 8 karakter.</li>
					<li>Password Anda tidak boleh berupa password yang umum digunakan.</li>
					<li>Password Anda tidak boleh sepenuhnya numerik.</li>
				</ul>
			</div>
			<div class="mb-3">
				<label for="inputPasswordConfirm" class="mb-1 block">Konfirmasi password</label>
				<input type="password" name="password2" id="inputPasswordConfirm" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-red-500 focus:invalid:ring-red-500 transition" required>
				<p class="text-xs">Masukkan password yang sama seperti sebelumnya, untuk verifikasi.</p>
			</div>
			<button class="py-2 px-3 bg-blue-600 text-white hover:bg-blue-700 disabled:bg-blue-400 focus:ring focus:ring-blue-200 rounded-md shadow-sm transition" type="submit">Daftar</button>
		</form>

		<p>Sudah mempunyai akun? <a href="{% url 'todolist:login' %}" class="text-blue-600 hover:text-blue-900 transition">Masuk</a>.</p>

	</div>
</body>


{% endblock content %}

todolist/templates/todolist-ajax.html
{% extends 'base_tw.html' %}
{% load static %}

{% block meta %}
<title>To-Do List • Hans TM @ Tugas PBP</title>
<!-- <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script> -->
<script defer src="{% static 'js/todolist-ajax.js' %}"></script>
<script>window.CSRF_TOKEN = "{{ csrf_token }}"</script>
{% endblock meta %}

{% block content %}
<body class="bg-gradient-to-br from-orange-600 to-amber-400 h-full min-h-screen w-full p-4">
	<!-- <div class="max-w-[48rem] min-w-[24rem] m-auto bg-white rounded-md p-8 shadow-lg">
	</div> -->

	<header class="bg-white p-2 rounded-md shadow-md mb-4 hover:shadow-xl transition">
		<nav class="flex gap-1 items-center flex-wrap">
			<div class="flex gap-1 items-center">
				<span class="px-2 py-2 rounded-md text-lg transition font-bold flex-grow">📝 To-Do List</span>
				<button id="add-open-modal-nav" class="py-2 px-4 rounded-md bg-slate-100 hover:bg-slate-300 transition sm:ml-0 flex-shrink">➕ Buat Task</button>	
			</div>
			<div class="flex gap-1 items-center flex-grow">
				<span id="page-status" class="mx-2 text-slate-500 flex-grow">Sedang memuat...</span>
				<span class="py-2 group relative flex-shrink">
					<span class="py-2 px-4 rounded-md bg-slate-100 hover:bg-slate-300 transition cursor-pointer">👤 {{ request.user }}</span>
					<div class="absolute pt-3 hidden group-hover:block right-0 transition">
						<div class="shadow-md rounded bg-white ring ring-slate-900/5 py-2 w-32">
							<a class="px-4 py-2 bg-white hover:bg-slate-200 w-full block transition" href="{% url 'todolist:logout' %}">🚪 Keluar</a>
						</div>
					</div>
		
				</span>
			</div>
		</nav>
	</header>

	<div id="wrapper"></div>

	<div id="add-modal" class="fixed z-10 w-screen inset-0 h-screen bg-black/30 hidden transition-opacity opacity-0 pt-4 px-4 md:pt-8">
		<div class="max-w-[48rem] m-auto bg-white rounded-md p-8 shadow-md hover:shadow-xl transition">
			<h1 class="text-4xl font-semibold mb-4">Buat Task</h1>
			<form id="add-form" class="mb-3">
				<div class="mb-3">
					<label for="inputTitle" class="mb-1 block">Judul</label>
					<input type="text" name="title" id="inputTitle" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-red-500 focus:invalid:ring-red-500 transition" required>
				</div>
				<div class="mb-3">
					<label for="inputDescription" class="mb-1 block">Keterangan</label>
					<textarea type="text" name="description" id="inputDescription" class="w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 mb-2 focus:invalid:border-pink-500 focus:invalid:ring-red-500 transition" required></textarea>
				</div>
				<button id="add-submit" class="py-2 px-3 bg-blue-600 text-white hover:bg-blue-700 disabled:bg-blue-400 focus:ring focus:ring-blue-200 rounded-md shadow-sm transition" type="submit">Tambah</button>
				<button id="add-close" class="py-2 px-3 mr-4 bg-slate-600 text-white hover:bg-slate-700 disabled:bg-slate-400 focus:ring focus:ring-slate-200 rounded-md shadow-sm transition">Batal</button>
			</form>
		</div>
	</div>
</body>

<template id="template-none">
	<div class="bg-white p-4 rounded-md shadow-md hover:shadow-xl transition">
		<p>Tidak ada task di sini. Ingin membuat task?</p>
		<div class="flex mt-3">
			<button class="py-2 px-3 bg-blue-600 text-white hover:bg-blue-700 disabled:bg-blue-400 focus:ring focus:ring-blue-200 rounded-md shadow-sm transition">➕ Buat Task</a>	
		</div>
	</div>
</template>

<template id="template-items">
	<div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-4">
	</div>
</template>

<template id="template-item">
	<div class="bg-white p-4 rounded-md flex shadow-md hover:shadow-xl transition">
		<div class="item-checkbox-wrapper mb-2 mr-4"></div>
		<div>
			<p class="item-title text-3xl mb-2">{{ item.title }}</p>
			<p class="item-description mb-2">{{ item.description }}</p>
			<p class="item-date text-sm text-slate-400 mb-2 ">{{ item.date|date:"j F Y" }}</p>
			<p>
				<button class="item-delete py-2 px-3 bg-red-600 text-white hover:bg-red-700 focus:ring focus:ring-red-200 rounded-md shadow-sm transition">Hapus</button>
			</p>
		</div>
	</div>
</template>

<template id="template-item-done">
	<button class="item-checkbox w-6 h-6 inline-block border-2 border-green-600 bg-green-500 text-white hover:bg-green-400 hover:border-green-500 relative rounded-sm transition"><span class="absolute -top-[0.4rem] left-[0.1rem] text-2xl">✓</span></button>
</template>

<template id="template-item-undone">
	<button class="item-checkbox w-6 h-6 inline-block border-2 border-slate-300 hover:border-slate-500 rounded-sm relative transition"></button>
</template>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base_tw.html' %}

{% block meta %}
<title>To-Do List • Hans TM @ Tugas PBP</title>
{% endblock meta %}

{% block content %}

<body class="bg-gradient-to-br from-orange-600 to-amber-400 h-full min-h-screen w-full p-4">
	<!-- <div class="max-w-[48rem] min-w-[24rem] m-auto bg-white rounded-md p-8 shadow-lg">
	</div> -->

	{% include 'navbar.html' %}
	
	<div class="bg-white p-4 rounded-md mb-4 shadow-md hover:shadow-xl transition">
		<h1 class="text-4xl font-semibold">To-Do List</h1>
		<p class="mt-4">Ditemukan {{ data|length }} task.</p>
		{% if messages %}
		<div class="bg-sky-200 py-2 px-3 mt-4 rounded-md border-sky-300 border-2">
			<ul>
				{% for message in messages %}
				<li>{{ message }}</li>
				{% endfor %}
			</ul>
		</div>
		{% endif %}
	</div>

	{% if data %}
	<div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-4">
		{% for item in data %}
		<div class="bg-white p-4 rounded-md flex shadow-md hover:shadow-xl transition">
			<form method="POST" class="mb-2 mr-4">
				{% csrf_token %}
				<input type="hidden" name="id" value="{{ item.pk }}">
				{% if item.is_finished %}
					<input type="hidden" name="action" value="undone">
					<button type="submit" class="w-6 h-6 inline-block border-2 border-green-600 bg-green-500 text-white hover:bg-green-400 hover:border-green-500 relative rounded-sm transition"><span class="absolute -top-[0.4rem] left-[0.1rem] text-2xl">✓</span></button>
				{% else %}
					<input type="hidden" name="action" value="done">
					<button type="submit" class="w-6 h-6 inline-block border-2 border-slate-300 hover:border-slate-500 rounded-sm relative transition"></button>
				{% endif %}
			</form>
			<div>
				<p class="text-3xl mb-2">{{ item.title }}</p>
				<p class="mb-2">{{ item.description }}</p>
				<p class="text-sm text-slate-400 mb-2">{{ item.date|date:"j F Y" }}</p>
				<p>
					<form method="POST">
						{% csrf_token %}
						<input type="hidden" name="id" value="{{ item.pk }}">
						<input type="hidden" name="action" value="delete">
						<button type="submit" class="py-2 px-3 bg-red-600 text-white hover:bg-red-700 focus:ring focus:ring-red-200 rounded-md shadow-sm transition">Hapus</button>
					</form>
				</p>
			</div>
		</div>
		{% endfor %}
	</div>
	{% else %}
	<div class="bg-white p-4 rounded-md shadow-md hover:shadow-xl transition">
		<p>Tidak ada task di sini. Ingin membuat task?</p>
		<div class="flex mt-3">
			<a href="{% url 'todolist:create_task' %}" class="py-2 px-3 bg-blue-600 text-white hover:bg-blue-700 disabled:bg-blue-400 focus:ring focus:ring-blue-200 rounded-md shadow-sm transition">➕ Buat Task</a>	
		</div>
	</div>
	{% endif %}

</body>

{% endblock content %}